app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

beer_filter_by_food:
  path: /api/beers/filterByFood?food={name}
  controller: App\Beers\Infrastructure\Controller\FilterByFoodController
  methods: [ GET ]

beer_by_id:
  path: /api/beers/{id}
  controller: App\Beers\Infrastructure\Controller\GetBeerById
  methods: [ GET ]
